name: Minimal Playwright Tests

on:
  workflow_dispatch:
    inputs:
      headed:
        description: 'Run in headed mode (visible browser)'
        required: false
        default: false
        type: boolean

jobs:
  minimal-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Minimal Tests
        run: |
          npx playwright test --project=minimal ${{ inputs.headed && '--headed' || '' }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
